spring:
  datasource:
    url: jdbc:mysql://localhost/alura_forum
    username: user
    password: password

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never