spring:
  datasource:
    url: jdbc:mysql://localhost/alura_forum
    username: name
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8585
  error:
    include-stacktrace: never

api:
  security:
    secret: ${JWT_SECRET:123456}

springdoc:
  api-docs:
    enable: true
  swagger-ui:
    enable: true
    path: /doc/swagger-ui.html